graph LR
  subgraph Заказчик
    C((Заказчик))
  end
  subgraph Фрилансер
    F((Фрилансер))
  end
  C --> UC1((Регистрация Авторизация))
  F --> UC1
  C --> UC2((Создание задания))
  C --> UC3((Редактирование задания))
  C --> UC4((Удаление задания))
  C --> UC5((Просмотр предложений))
  C --> UC6((Принятие отклонение предложения))
  C --> UC7((Обмен сообщениями))
  C --> UC8((Оставление отзыва))
  F --> UC9((Поиск заданий))
  F --> UC10((Подача предложения))
  F --> UC11((Отзыв предложения))
  F --> UC7
  F --> UC12((Ведение публикаций))
  F --> UC13((Редактирование профиля))